
project_id = "bgidfcqktsttzlwlumtz"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[realtime]
enabled = true

[studio]
enabled = false

[inbucket]
enabled = false

[auth]
enabled = true

[storage]
enabled = false
