
project_id = "bgidfcqktsttzlwlumtz"

[functions.ai-wedding-assistant]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.generate-checklist-ai]
verify_jwt = true

[functions.send-auth-email]
verify_jwt = false

[functions.google-venues-scraper]
verify_jwt = false
