// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-prestataires.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.49.4";
import { z } from "npm:zod@^3.23.8";
function anonSupabase() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var search_prestataires_default = defineTool({
  name: "search_prestataires",
  title: "Rechercher des prestataires",
  description: "Rechercher des prestataires de mariage visibles dans l'annuaire Mariable (lieux, traiteurs, photographes, etc.). Retourne nom, cat\xE9gorie, ville, prix, description, slug.",
  inputSchema: {
    query: z.string().optional().describe("Texte libre recherch\xE9 dans le nom ou la description"),
    categorie: z.string().optional().describe("Cat\xE9gorie exacte (ex: Lieu de r\xE9ception, Traiteur, Photographe)"),
    ville: z.string().optional().describe("Filtrer par ville"),
    limit: z.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, categorie, ville, limit }) => {
    const supabase = anonSupabase();
    let q = supabase.from("prestataires_rows").select(
      "id,nom,slug,categorie,ville,description,prix_a_partir_de,prix_par_personne,site_web,google_rating"
    ).eq("visible", true).limit(limit);
    if (categorie) q = q.eq("categorie", categorie);
    if (ville) q = q.ilike("ville", `%${ville}%`);
    if (query) q = q.or(`nom.ilike.%${query}%,description.ilike.%${query}%`);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-blog-posts.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.49.4";
import { z as z2 } from "npm:zod@^3.23.8";
function anonSupabase2() {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var list_blog_posts_default = defineTool2({
  name: "list_blog_posts",
  title: "Lister les articles de blog",
  description: "Lister les articles de conseils mariage publi\xE9s sur Mariable. Retourne titre, slug, cat\xE9gorie, extrait.",
  inputSchema: {
    category: z2.string().optional().describe("Filtrer par cat\xE9gorie"),
    limit: z2.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, limit }) => {
    const supabase = anonSupabase2();
    let q = supabase.from("blog_posts").select("id,slug,title,subtitle,category,meta_description,published_at").eq("status", "published").order("published_at", { ascending: false }).limit(limit);
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.49.4";
function userSupabase(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_my_profile_default = defineTool3({
  name: "get_my_profile",
  title: "Mon profil Mariable",
  description: "Retourne le profil Mariable de l'utilisateur connect\xE9 (email, nom, date de mariage pr\xE9vue, statut premium).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const supabase = userSupabase(ctx);
    const { data, error } = await supabase.from("profiles").select("*").eq("id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? {}) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/list-my-wedding-projects.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.49.4";
import { z as z3 } from "npm:zod@^3.23.8";
function userSupabase2(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_my_wedding_projects_default = defineTool4({
  name: "list_my_wedding_projects",
  title: "Mes projets de mariage",
  description: "Lister les projets de mariage (VibeWedding) de l'utilisateur connect\xE9 : titre, r\xE9sum\xE9, budget, planning, prestataires.",
  inputSchema: {
    limit: z3.number().int().min(1).max(20).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const supabase = userSupabase2(ctx);
    const { data, error } = await supabase.from("wedding_projects").select("id,title,summary,budget_breakdown,timeline,vendors,wedding_data,updated_at").eq("user_id", ctx.getUserId()).order("updated_at", { ascending: false }).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { projects: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "bgidfcqktsttzlwlumtz";
var mcp_default = defineMcp({
  name: "mariable-mcp",
  title: "Mariable",
  version: "0.1.0",
  instructions: "Outils pour Mariable, plateforme d'organisation de mariage. Utilisez `search_prestataires` et `list_blog_posts` pour la recherche publique. `get_my_profile` et `list_my_wedding_projects` retournent les donn\xE9es du compte connect\xE9.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_prestataires_default, list_blog_posts_default, get_my_profile_default, list_my_wedding_projects_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
